apiVersion: v1
kind: Service
metadata:
  name: history-service
  labels:
    app: history-service
spec:
  selector:
    app: history-service
  type: ClusterIP
  ports:
    - name: hist-service
      port: 8005
      targetPort: 8005
