apiVersion: apps/v1
kind: Deployment
metadata:
  name: history-service
  labels:
    app: history-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: history-service
  template:
    metadata:
      labels:
        app: history-service
    spec:
      containers:
        - name: history-service
          image: asia-southeast1-docker.pkg.dev/crucial-mender-402111/peerprep/history:latest
          ports:
            - name: hist-service
              containerPort: 8005
          env:	
          - name: DB_USERNAME	
            valueFrom:	
              secretKeyRef:	
                name: db-admin	
                key: db-username	
          - name: DB_PASSWORD	
            valueFrom:	
              secretKeyRef:	
                name: db-admin	
                key: db-password
      restartPolicy: Always
